#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
Django settings for PyScadaServer project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'r(+62_iyns0$-8y3#nc7m_h%$mua%5b2dgps66t+t4v92^=r)#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pyscada',
    'pyscada.hmi',
    'pyscada.export',
    'pyscada.modbus',
    'pyscada.systemstat',
    'pyscada.phant',
    'pyscada.smbus',
    'pyscada.onewire',
    'pyscada.visa'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PyScadaServer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PyScadaServer.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'PyScada_db',
        'USER': 'PyScada-user',
        'PASSWORD': 'PyScada-user-password',
        'HOST':'db',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = '/http/static/'

MEDIA_URL = '/media/'

MEDIA_ROOT = '/http/media/'

# email settings
DEFAULT_FROM_EMAIL = 'pyscada@martin-schroeder.net'
EMAIL_HOST = '95.143.172.178'  # 'mail.dorado.uberspace.de'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'pyscada@martin-schroeder.net'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_PASSWORD = 'pyscada-automail-host-qsdr3?7.!>j'
EMAIL_PREFIX = 'TUKT_Test'

# PyScada settings
# https://github.com/trombastic/PyScada

# 
PYSCADA_META = {
    'name': 'TUKT_test',  # FIXME
    'description': 'Testdatensätze, Technische Universität Berlin, Gebäude KT'  # FIXME
}

# settings for the PYSCADA Export Module
# 
# output_folder			folder were the exported files will be stored
#
# file_prefix           prefix of the output files (PREFIXmeasurement_data_Y_m_d_HM.[h5,csv])

PYSCADA_EXPORT = {
    'output_folder': '/src/http/measurement_data_dumps',
    'file_prefix': PYSCADA_META['name'] + '_'
}
