#!/bin/bash
 
NAME="PyScada_gunicorn"                           # Name of the application
DJANGODIR=`pwd`				          			  # Django project directory
SOCKFILE="$DJANGODIR/run/gunicorn.sock"   	      # we will communicte using this unix socket
USER=`whoami`                                     # the user to run as
GROUP=$(id -gn)                                   # the group to run as
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE="$1.settings"              # which settings file should Django use
DJANGO_WSGI_MODULE="$1.wsgi"                      # WSGI module name


echo "Starting $NAME as $GROUP:`whoami`"
#echo $DJANGODIR
#echo $SOCKFILE
#echo $USER
#echo $DJANGO_SETTINGS_MODULE
#echo $DJANGO_WSGI_MODULE
#echo $GROUP
 
# Activate the virtual environment
#cd $DJANGODIR
#source ../bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH
 
# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR
 
# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=debug \
  --bind=unix:$SOCKFILE

