# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0041_update_protocol_id'),
        ('smbus', '0002_auto_20170225_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedSMBusDevice',
            fields=[
            ],
            options={
                'verbose_name': 'SMBus Device',
                'proxy': True,
                'verbose_name_plural': 'SMBus Devices',
                'indexes': [],
            },
            bases=('pyscada.device',),
        ),
        migrations.CreateModel(
            name='ExtendedSMbusVariable',
            fields=[
            ],
            options={
                'verbose_name': 'SMBus Variable',
                'proxy': True,
                'verbose_name_plural': 'SMBus Variables',
                'indexes': [],
            },
            bases=('pyscada.variable',),
        ),
    ]
