# Generated by Django 2.2.6 on 2019-10-04 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smbus', '0003_extendedsmbusdevice_extendedsmbusvariable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smbusdevice',
            name='smbus_device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyscada.Device'),
        ),
        migrations.AlterField(
            model_name='smbusvariable',
            name='smbus_variable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyscada.Variable'),
        ),
    ]
