# Generated by Django 3.2 on 2023-02-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smbus', '0012_devicehandler_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smbusdevice',
            name='instrument_handler',
        ),
    ]
