# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visadevicehandler',
            name='handler_path',
            field=models.CharField(blank=True, default=None, help_text=b'', max_length=255, null=True),
        ),
    ]
