# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0003_auto_20170225_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visadevicehandler',
            name='handler_path',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
