# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0039_auto_20170711_1326'),
        ('visa', '0004_auto_20170711_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedVISADevice',
            fields=[
            ],
            options={
                'verbose_name': 'VISA Device',
                'proxy': True,
                'verbose_name_plural': 'VISA Devices',
                'indexes': [],
            },
            bases=('pyscada.device',),
        ),
        migrations.CreateModel(
            name='ExtendedVISAVariable',
            fields=[
            ],
            options={
                'verbose_name': 'VISA Variable',
                'proxy': True,
                'verbose_name_plural': 'VISA Variable',
                'indexes': [],
            },
            bases=('pyscada.variable',),
        ),
    ]
