# Generated by Django 2.2.8 on 2021-06-01 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0079_devicehandler'),
        ('visa', '0008_auto_20191004_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='visadevice',
            name='instrument_handler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyscada.DeviceHandler'),
        ),
    ]
