# Generated by Django 2.2.8 on 2021-06-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0010_devicehandler_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visadevice',
            name='instrument',
        ),
    ]
