# Generated by Django 3.2 on 2023-02-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0014_devicehandler_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visadevice',
            name='instrument_handler',
        ),
    ]
