# Generated by Django 3.2 on 2023-02-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0015_remove_visadevice_instrument_handler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visadevice',
            name='resource_name',
            field=models.CharField(default='GPIB0::22::INSTR', help_text="Examples :<br>for GPIB instruments : GPIB0::22::INSTR<br>for TCPIP/LXI instruments : TCPIP::192.168.228.104::INSTR<br>for USB instruments : USB0::0x1AB1::0x4CE::DS1ZA181806919::INSTR<br>for Serial instruments : ASRL/dev/ttyUSB0::INSTR<br>more information <a href='https://pyvisa.readthedocs.io/en/stable/introduction/communication.html'>here</a>", max_length=255),
        ),
    ]
