# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modbus', '0005_auto_20170224_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modbusvariable',
            name='function_code_read',
            field=models.PositiveSmallIntegerField(choices=[(0, 'not selected'), (1, 'coils (FC1)'), (2, 'discrete inputs (FC2)'), (3, 'holding registers (FC3)'), (4, 'input registers (FC4)')], default=0),
        ),
    ]
