# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0039_auto_20170711_1326'),
        ('modbus', '0006_auto_20170711_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedModbusDevice',
            fields=[
            ],
            options={
                'verbose_name': 'Modbus Device',
                'proxy': True,
                'verbose_name_plural': 'Modbus Devices',
                'indexes': [],
            },
            bases=('pyscada.device',),
        ),
        migrations.CreateModel(
            name='ExtendedModbusVariable',
            fields=[
            ],
            options={
                'verbose_name': 'Modbus Variable',
                'proxy': True,
                'verbose_name_plural': 'Modbus Variables',
                'indexes': [],
            },
            bases=('pyscada.variable',),
        ),
    ]
