# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0030_device_polling_interval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariableConfigFileImport',
        ),
    ]
