# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("export", "0015_remove_exporttask_backgroundtask"),
        ("pyscada", "0039_auto_20170711_1326"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BackgroundTask",
        ),
        migrations.AlterField(
            model_name="backgroundprocess",
            name="process_class_kwargs",
            field=models.CharField(
                blank=True,
                default="{}",
                help_text='arguments in json format will be passed as kwargs while the \n                                            init of the process instance, example: \n                                            {"keywordA":"value1", "keywordB":7}',
                max_length=400,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="action",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "just record"),
                    (1, "record and send mail only when event occurs"),
                    (2, "record and send mail"),
                    (3, "record, send mail and change variable"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="variable_limit",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="you can choose either an fixed limit or an variable limit that is\n                                        dependent on the current value of an variable, if you choose a value other then \n                                        none for variable limit the fixed limit would be ignored",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variable_limit",
                to="pyscada.Variable",
            ),
        ),
    ]
