# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0042_auto_20180604_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicewritetask',
            name='property_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
