# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0045_auto_20180705_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicewritetask',
            name='property_name',
        ),
    ]
