# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0046_remove_devicewritetask_property_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='variableproperty',
            name='unit',
            field=models.ForeignKey(default='', on_delete=models.SET(1), to='pyscada.Unit'),
        ),
    ]
