# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0048_datamigration_20181025_0918'),
    ]

    operations = [
        migrations.RenameModel('RecordedData', 'RecordedDataOld'),
        migrations.RenameModel('RecordedDataNew', 'RecordedData'),
    ]
