# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pyscada", "0047_variableproperty_unit"),
        ("pyscada", "0049_auto_20181025_1049"),
    ]

    operations = []
