# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-06 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pyscada", "0050_merge_20181130_1143"),
    ]

    operations = [
        migrations.AddField(
            model_name="variable",
            name="value_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variable",
            name="value_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variableproperty",
            name="value_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variableproperty",
            name="value_min",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
