# Generated by Django 2.2.8 on 2019-12-06 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pyscada", "0057_auto_20191004_0912"),
        ("pyscada", "0054_auto_20190208_0913"),
    ]

    operations = []
