# Generated by Django 2.2.8 on 2020-10-05 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pyscada", "0063_complexevent_complexeventitem_complexeventitemvariable"),
    ]

    operations = [
        migrations.RenameField(
            model_name="complexevent",
            old_name="mail_recipients",
            new_name="complex_mail_recipients",
        ),
        migrations.AddField(
            model_name="complexeventitem",
            name="custom_validation",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.AddField(
            model_name="complexeventitem",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="complexeventitem",
            name="stop_recording",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="complexeventitem",
            name="validation",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "OR"), (1, "AND"), (2, "Custom")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="complexeventitemvariable",
            name="limit_low_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "limit < value"), (1, "limit <= value")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="complexeventitemvariable",
            name="variable_limit_high",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="you can choose either an \n                                            fixed limit or an variable limit that is dependent on the current value of \n                                            an variable, if you choose a value other than  none for variable limit the \n                                            fixed limit would be ignored",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variable_limit_high",
                to="pyscada.Variable",
            ),
        ),
        migrations.AlterField(
            model_name="complexeventitemvariable",
            name="variable_limit_low",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="you can choose either an \n                                            fixed limit or an variable limit that is dependent on the current value of \n                                            an variable, if you choose a value other than  none for variable limit the \n                                            fixed limit would be ignored",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variable_limit_low",
                to="pyscada.Variable",
            ),
        ),
    ]
