# Generated by Django 2.2.8 on 2020-10-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pyscada", "0068_auto_20201006_0826"),
    ]

    operations = [
        migrations.AddField(
            model_name="complexeventgroup",
            name="current_level",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
