# Generated by Django 2.2.8 on 2020-10-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0071_recordedevent_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordedevent',
            name='level',
        ),
        migrations.AddField(
            model_name='complexeventgroup',
            name='last_level',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
