# Generated by Django 2.2.8 on 2020-10-07 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0072_auto_20201006_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complexevent',
            old_name='complex_event',
            new_name='complex_event_group',
        ),
    ]
