# Generated by Django 2.2.8 on 2020-10-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pyscada", "0073_auto_20201007_0858"),
    ]

    operations = [
        migrations.AddField(
            model_name="complexeventitem",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
