# Generated by Django 2.2.8 on 2020-10-07 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0074_complexeventitem_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complexevent',
            name='change_value',
        ),
        migrations.AddField(
            model_name='complexeventgroup',
            name='default_send_mail',
            field=models.BooleanField(default=False, help_text='Send mail if no activated event'),
        ),
        migrations.AddField(
            model_name='complexeventgroup',
            name='default_value',
            field=models.FloatField(blank=True, default=None, help_text='Set if no activated event', null=True),
        ),
        migrations.AlterField(
            model_name='complexevent',
            name='new_value',
            field=models.FloatField(blank=True, default=None, help_text='For the group variable to change', null=True),
        ),
        migrations.AlterField(
            model_name='complexeventgroup',
            name='variable_to_change',
            field=models.ForeignKey(blank=True, default=None, help_text='Change the value on event changes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complex_variable_to_change', to='pyscada.Variable'),
        ),
    ]
