# Generated by Django 2.2.8 on 2020-10-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0075_auto_20201007_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='html_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
