# Generated by Django 2.2.8 on 2020-11-04 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0076_mail_html_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordeddata',
            name='variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyscada.Variable'),
        ),
        migrations.AlterField(
            model_name='recordeddataold',
            name='variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyscada.Variable'),
        ),
    ]
