# Generated by Django 2.2.8 on 2021-07-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pyscada", "0079_devicehandler"),
    ]

    operations = [
        migrations.AddField(
            model_name="variableproperty",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
