# Generated by Django 2.2.8 on 2021-11-17 10:23

import datetime
from django.db import migrations, models
from datetime import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("pyscada", "0087_auto_20211116_1329"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extendedcalculatedvariable",
            options={
                "verbose_name": "Calculated variable",
                "verbose_name_plural": "Calculated variables",
            },
        ),
        migrations.AlterField(
            model_name="periodicfield",
            name="start_from",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 11, 17, 0, 0, tzinfo=timezone.utc),
                help_text="Calculate from this DateTime and then each period_factor*period",
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="name",
            field=models.SlugField(
                max_length=200, unique=True, verbose_name="variable name"
            ),
        ),
    ]
