# Generated by Django 2.2.8 on 2021-11-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0089_calculatedvariable_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatedvariable',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
