# Generated by Django 2.2.8 on 2021-11-25 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pyscada", "0092_auto_20211125_1054"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="", max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="DictionaryItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(default="", max_length=400)),
                ("value", models.CharField(default="", max_length=400)),
                (
                    "dictionary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pyscada.Dictionary",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="variable",
            name="dictionary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pyscada.Dictionary",
            ),
        ),
    ]
