# Generated by Django 3.2 on 2023-02-06 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0099_alter_dictionaryitem_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='instrument_handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyscada.devicehandler'),
        ),
    ]
