# Generated by Django 4.2 on 2023-04-24 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pyscada", "0102_move_complex_event_variables"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complexevent",
            name="new_value",
        ),
        migrations.RemoveField(
            model_name="complexeventgroup",
            name="default_value",
        ),
        migrations.RemoveField(
            model_name="complexeventgroup",
            name="variable_to_change",
        ),
    ]
