# Generated by Django 4.2.2 on 2023-12-13 11:11

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    DataSourceModel = apps.get_model("pyscada", "DataSourceModel")
    DataSource = apps.get_model("pyscada", "DataSource")
    DjangoDatabase = apps.get_model("pyscada", "DjangoDatabase")
    db_alias = schema_editor.connection.alias
    dsm, _ = DataSourceModel.objects.using(db_alias).update_or_create(
        inline_model_name="DjangoDatabase",
        defaults={
            "name": "Django database",
            "can_add": False,
            "can_change": False,
            "can_select": True,
        },
    )
    ds, _ = DataSource.objects.using(db_alias).update_or_create(
        id=1,
        defaults={
            "datasource_model": dsm,
        },
    )
    dd, _ = DjangoDatabase.objects.using(db_alias).update_or_create(
        datasource=ds,
        defaults={
            "data_model_app_name": "pyscada",
            "data_model_name": "RecordedData",
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("pyscada", "0105_edit_generic_device_protocol"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataSourceModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("inline_model_name", models.CharField(max_length=100)),
                (
                    "can_add",
                    models.BooleanField(
                        default=False,
                        help_text="True to enable custom data sources of this type to be added from the administration panel.",
                    ),
                ),
                (
                    "can_change",
                    models.BooleanField(
                        default=False,
                        help_text="True to enable custom data sources of this type to be modified from the administration panel.",
                    ),
                ),
                (
                    "can_select",
                    models.BooleanField(
                        default=True,
                        help_text="False to hide this type of custom data source in the variable administration panel.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DjangoDatabase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_model_app_name", models.CharField(max_length=50)),
                ("data_model_name", models.CharField(max_length=50)),
                (
                    "datasource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pyscada.datasource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="datasource",
            name="datasource_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pyscada.datasourcemodel",
            ),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.AddField(
            model_name="variable",
            name="datasource",
            field=models.ForeignKey(
                default=1,
                help_text="Select a custom data source to read/write data for this variable.",
                on_delete=models.SET(1),
                to="pyscada.datasource",
            ),
        ),
    ]
