# Generated by Django 4.2.5 on 2023-12-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pyscada", "0106_datasource_datasourcemodel_djangodatabase_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculatedvariableselector",
            name="period_fields",
            field=models.ManyToManyField(blank=True, to="pyscada.periodicfield"),
        ),
    ]
