# Generated by Django 4.2.5 on 2024-01-16 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pyscada", "0107_alter_calculatedvariableselector_period_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calculatedvariable",
            name="period",
        ),
        migrations.RemoveField(
            model_name="calculatedvariable",
            name="store_variable",
        ),
        migrations.RemoveField(
            model_name="calculatedvariable",
            name="variable_calculated_fields",
        ),
        migrations.RemoveField(
            model_name="calculatedvariableselector",
            name="main_variable",
        ),
        migrations.RemoveField(
            model_name="calculatedvariableselector",
            name="period_fields",
        ),
        migrations.DeleteModel(
            name="ExtendedCalculatedVariable",
        ),
        migrations.DeleteModel(
            name="CalculatedVariable",
        ),
        migrations.DeleteModel(
            name="CalculatedVariableSelector",
        ),
        migrations.DeleteModel(
            name="PeriodicField",
        ),
    ]
