# Generated by Django 4.2.5 on 2024-02-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pyscada", "0108_remove_calculatedvariable_period_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variable",
            name="value_class",
            field=models.CharField(
                choices=[
                    ("FLOAT32", "REAL, SINGLE or FLOAT32"),
                    ("UNIXTIMEF32", "UNIXTIMEF32"),
                    ("FLOAT64", "LREAL, FLOAT, DOUBLE or FLOAT64"),
                    ("UNIXTIMEF64", "UNIXTIMEF64"),
                    ("FLOAT48", "FLOAT48"),
                    ("INT64", "INT64"),
                    ("UINT64", "UINT64"),
                    ("UNIXTIMEI64", "UNIXTIMEI64"),
                    ("INT48", "INT48"),
                    ("UNIXTIMEI32", "UNIXTIMEI32"),
                    ("INT32", "INT32"),
                    ("UINT32", "DWORD or UINT32"),
                    ("INT16", "INT or INT16"),
                    ("UINT16", "WORD, UINT or UINT16"),
                    ("INT8", "INT8"),
                    ("UINT8", "UINT8"),
                    ("BOOLEAN", "BOOL or BOOLEAN"),
                ],
                default="FLOAT64",
                max_length=15,
                verbose_name="value_class",
            ),
        ),
    ]
