# Generated by Django 5.0.3 on 2024-07-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pyscada", "0109_alter_variable_value_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="variable",
            name="readable",
            field=models.BooleanField(default=True),
        ),
    ]
