# Generated by Django 5.1.6 on 2025-06-02 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pyscada", "0110_variable_readable"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceHandlerParameter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pyscada.device"
                    ),
                ),
            ],
        ),
    ]
