# Generated by Django 5.1.6 on 2025-06-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pyscada", "0111_devicehandlerparameter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicehandlerparameter",
            name="value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
