# Generated by Django 5.1.6 on 2025-06-06 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pyscada", "0112_alter_devicehandlerparameter_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariableHandlerParameter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pyscada.variable",
                    ),
                ),
            ],
        ),
    ]
