# Generated by Django 5.1.6 on 2025-06-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pyscada", "0113_variablehandlerparameter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicehandlerparameter",
            name="value",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="variablehandlerparameter",
            name="value",
            field=models.CharField(default="", max_length=255),
        ),
    ]
