# Generated by Django 5.2.10 on 2026-02-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0114_alter_devicehandlerparameter_value_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='recordeddata',
                    name='variable',
                ),
                migrations.RemoveField(
                    model_name='recordeddataold',
                    name='variable',
                ),
                migrations.DeleteModel(
                    name='DjangoDatabase',
                ),
                migrations.DeleteModel(
                    name='RecordedData',
                ),
                migrations.DeleteModel(
                    name='RecordedDataOld',
                ),
            ],
            database_operations=[],
        ),
    ]
