# Generated by Django 5.2.10 on 2026-02-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0115_remove_recordeddata_variable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='pause_recording',
            field=models.BooleanField(default=False, help_text='data will be discarded entirely while True'),
        ),
    ]
