# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pyscada', '0033_auto_20161107_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneWireVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', help_text='64bit Sensor Address', max_length=400)),
                ('sensor_type', models.CharField(choices=[('DS18B20', 'DS18B20 Temperature Sensor')], default='', max_length=10)),
                ('onewire_variable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyscada.Variable')),
            ],
        ),
    ]
