# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onewire', '0003_onewiredevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onewiredevice',
            name='adapter_type',
            field=models.CharField(choices=[(b'owserver', b'OWFS owserver'), (b'rpi_gpio4', b'RPi GPIO 4')], default=b'', max_length=400),
        ),
    ]
