# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemstat', '0005_extendedsystemstatdevice_extendedsystemstatvariable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extendedsystemstatvariable',
            options={'verbose_name': 'SystemStat Variable', 'verbose_name_plural': 'SystemStat Variables'},
        ),
    ]
