# Generated by Django 2.2.6 on 2019-10-04 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemstat', '0007_auto_20170916_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstatvariable',
            name='system_stat_variable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyscada.Variable'),
        ),
    ]
