#!/usr/bin/env sh
while ! wget --quiet db:3306; do
    sleep 1
done
python3 /src/pyscada/manage.py migrate
python3 /src/pyscada/manage.py collectstatic --no-input
python3 /src/pyscada/manage.py loaddata color
python3 /src/pyscada/manage.py loaddata units
python3 /src/pyscada/manage.py pyscada_daemon init