# Generated by Django 5.2.10 on 2026-02-10 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pyscada', '0116_variable_pause_recording'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lifetime', models.PositiveIntegerField(default=3600)),
                ('datasource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyscada.datasource')),
            ],
        ),
    ]
