# Generated by Django 5.2.10 on 2026-02-12 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pyscada', '0116_variable_pause_recording'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoSingleValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyscada.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='SingleValueRecordedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saved', models.DateTimeField(db_index=True)),
                ('value_boolean', models.BooleanField(blank=True, default=False)),
                ('value_int16', models.SmallIntegerField(blank=True, null=True)),
                ('value_int32', models.IntegerField(blank=True, null=True)),
                ('value_int64', models.BigIntegerField(blank=True, null=True)),
                ('value_float64', models.FloatField(blank=True, null=True)),
                ('timestamp', models.FloatField(db_index=True)),
                ('variable', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyscada.variable')),
            ],
        ),
    ]
