# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("export", "0006_auto_20160404_0949"),
    ]

    operations = [
        migrations.AddField(
            model_name="exporttask",
            name="datetime_fineshed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exporttask",
            name="datetime_max",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="exporttask",
            name="datetime_min",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="exporttask",
            name="datetime_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
