# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("export", "0014_auto_20170711_1326"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exporttask",
            name="backgroundtask",
        ),
    ]
