# Generated by Django 2.2.6 on 2019-10-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0015_remove_exporttask_backgroundtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporttask',
            name='busy',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='exporttask',
            name='done',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='exporttask',
            name='failed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='scheduledexporttask',
            name='active',
            field=models.BooleanField(blank=True, default=False, help_text='to activate scheduled export'),
        ),
    ]
