# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0008_auto_20180620_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlitem',
            name='property_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
