# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0045_auto_20180705_1341'),
        ('hmi', '0009_controlitem_property_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlitem',
            name='property_name',
        ),
        migrations.AddField(
            model_name='controlitem',
            name='variable_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pyscada.VariableProperty'),
        ),
    ]
