# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0046_remove_devicewritetask_property_name'),
        ('hmi', '0011_auto_20180710_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=400)),
                ('button', models.CharField(default='Ok', max_length=50)),
                ('hidden_variables_set_up', models.ManyToManyField(related_name='Hidden_Variables_Form', to='pyscada.Variable')),
                ('variables', models.ManyToManyField(related_name='Variables_Form', to='pyscada.Variable')),
            ],
        ),
        migrations.CreateModel(
            name='XY_Chart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=400)),
                ('x_axis_label', models.CharField(blank=True, default='', max_length=400)),
                ('x_axis_linlog', models.BooleanField(default=False, help_text='False->Lin / True->Log')),
                ('y_axis_label', models.CharField(blank=True, default='', max_length=400)),
                ('variables', models.ManyToManyField(related_name='Variables_XY_Chart', to='pyscada.Variable')),
                ('x_axis_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='X_axis_type', to='pyscada.Variable')),
            ],
        ),
        migrations.AddField(
            model_name='groupdisplaypermission',
            name='xy_charts',
            field=models.ManyToManyField(blank=True, to='hmi.XY_Chart'),
        ),
        migrations.AddField(
            model_name='widget',
            name='xy_chart',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hmi.XY_Chart'),
        ),
    ]
