# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('hmi', '0012_auto_20180718_0834'), ('hmi', '0013_auto_20180718_1415')]

    dependencies = [
        ('pyscada', '0046_remove_devicewritetask_property_name'),
        ('hmi', '0011_auto_20180710_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=400)),
                ('button', models.CharField(default='Ok', max_length=50)),
                ('control_items', models.ManyToManyField(related_name='control_items_form', to=b'hmi.ControlItem')),
                ('hidden_control_items_to_true', models.ManyToManyField(related_name='hidden_control_items_form', to=b'hmi.ControlItem')),
            ],
        ),
        migrations.AddField(
            model_name='groupdisplaypermission',
            name='xy_charts',
            field=models.ManyToManyField(blank=True, to=b'hmi.XYChart'),
        ),
        migrations.AddField(
            model_name='widget',
            name='xy_chart',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hmi.XYChart'),
        ),
        migrations.CreateModel(
            name='XYChart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=400)),
                ('x_axis_label', models.CharField(blank=True, default='', max_length=400)),
                ('x_axis_linlog', models.BooleanField(default=False, help_text='False->Lin / True->Log')),
                ('y_axis_label', models.CharField(blank=True, default='', max_length=400)),
                ('variables', models.ManyToManyField(related_name='variables_xy_chart', to=b'pyscada.Variable')),
                ('x_axis_var', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='x_axis_var', to='pyscada.Variable')),
            ],
        ),
        migrations.AddField(
            model_name='controlpanel',
            name='forms',
            field=models.ManyToManyField(blank=True, to=b'hmi.Form'),
        ),
    ]
