# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0046_remove_devicewritetask_property_name'),
        ('hmi', '0012_auto_20180718_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='XYChart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=400)),
                ('x_axis_label', models.CharField(blank=True, default='', max_length=400)),
                ('x_axis_linlog', models.BooleanField(default=False, help_text='False->Lin / True->Log')),
                ('y_axis_label', models.CharField(blank=True, default='', max_length=400)),
                ('variables', models.ManyToManyField(related_name='variables_xy_chart', to='pyscada.Variable')),
                ('x_axis_var', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='x_axis_var', to='pyscada.Variable')),
            ],
        ),
        migrations.RemoveField(
            model_name='xy_chart',
            name='variables',
        ),
        migrations.RemoveField(
            model_name='xy_chart',
            name='x_axis_type',
        ),
        migrations.RemoveField(
            model_name='form',
            name='hidden_variables_set_up',
        ),
        migrations.RemoveField(
            model_name='form',
            name='variables',
        ),
        migrations.AddField(
            model_name='controlpanel',
            name='forms',
            field=models.ManyToManyField(blank=True, to='hmi.Form'),
        ),
        migrations.AddField(
            model_name='form',
            name='control_items',
            field=models.ManyToManyField(related_name='control_items_form', to='hmi.ControlItem'),
        ),
        migrations.AddField(
            model_name='form',
            name='hidden_control_items_to_true',
            field=models.ManyToManyField(related_name='hidden_control_items_form', to='hmi.ControlItem'),
        ),
        migrations.AlterField(
            model_name='groupdisplaypermission',
            name='xy_charts',
            field=models.ManyToManyField(blank=True, to='hmi.XYChart'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='xy_chart',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hmi.XYChart'),
        ),
        migrations.DeleteModel(
            name='XY_Chart',
        ),
    ]
