# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0012_auto_20180719_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='show_timeline',
            field=models.BooleanField(default=True),
        ),
    ]
