# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-13 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0047_variableproperty_unit'),
        ('hmi', '0014_auto_20180912_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=400)),
                ('button', models.CharField(default='Ok', max_length=50)),
                ('control_items', models.ManyToManyField(related_name='control_items_form', to='hmi.ControlItem')),
                ('hidden_control_items_to_true', models.ManyToManyField(related_name='hidden_control_items_form', to='hmi.ControlItem')),
            ],
        ),
        migrations.CreateModel(
            name='XYChart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=400)),
                ('x_axis_label', models.CharField(blank=True, default='', max_length=400)),
                ('x_axis_linlog', models.BooleanField(default=False, help_text='False->Lin / True->Log')),
                ('y_axis_label', models.CharField(blank=True, default='', max_length=400)),
                ('variables', models.ManyToManyField(related_name='variables_xy_chart', to='pyscada.Variable')),
                ('x_axis_var', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='x_axis_var', to='pyscada.Variable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='view',
            name='show_timeline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='controlpanel',
            name='forms',
            field=models.ManyToManyField(blank=True, to='hmi.Form'),
        ),
        migrations.AddField(
            model_name='groupdisplaypermission',
            name='xy_charts',
            field=models.ManyToManyField(blank=True, to='hmi.XYChart'),
        ),
    ]
