# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-26 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0016_auto_20181004_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdisplaypermission',
            name='forms',
            field=models.ManyToManyField(blank=True, to='hmi.Form'),
        ),
    ]
