# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-05 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pyscada", "0050_merge_20181130_1143"),
        ("hmi", "0018_auto_20181205_0937"),
    ]

    operations = [
        migrations.AddField(
            model_name="dropdown",
            name="variable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pyscada.Variable",
            ),
        ),
        migrations.AddField(
            model_name="dropdown",
            name="variable_property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pyscada.VariableProperty",
            ),
        ),
    ]
