# Generated by Django 2.2.7 on 2019-11-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hmi", "0022_auto_20191004_0912"),
    ]

    operations = [
        migrations.AddField(
            model_name="dropdownitem",
            name="value",
            field=models.CharField(default="", max_length=400),
        ),
    ]
