# Generated by Django 2.2.8 on 2019-12-12 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0023_dropdownitem_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlitem',
            name='variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pyscada.Variable'),
        ),
        migrations.AlterField(
            model_name='controlitem',
            name='variable_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pyscada.VariableProperty'),
        ),
    ]
