# Generated by Django 2.2.8 on 2020-09-15 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0061_devicereadtask'),
        ('hmi', '0025_widgetcontent_content_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlitem',
            name='color_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_1', to='pyscada.Color'),
        ),
        migrations.AddField(
            model_name='controlitem',
            name='color_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_2', to='pyscada.Color'),
        ),
        migrations.AddField(
            model_name='controlitem',
            name='color_3',
            field=models.ForeignKey(blank=True, help_text='Only needed for 3 colors', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_3', to='pyscada.Color'),
        ),
        migrations.AddField(
            model_name='controlitem',
            name='color_level_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controlitem',
            name='color_level_2',
            field=models.PositiveSmallIntegerField(default=50, help_text='Only needed for 3 colors and gradient'),
        ),
        migrations.AddField(
            model_name='controlitem',
            name='display_type_color',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Value only'), (1, 'Color only'), (2, 'Value and color')], default=0),
        ),
        migrations.AddField(
            model_name='controlitem',
            name='display_value_color',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No color'), (1, '2 color'), (2, '3 colors'), (3, 'color gradient')], default=0, help_text='For boolean no level needed and will use color 1 and 2'),
        ),
        migrations.AddField(
            model_name='controlitem',
            name='display_value_transformation',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Timestamp to local date'), (2, 'Dictionary')], default=0),
        ),
        migrations.AddField(
            model_name='controlitem',
            name='display_value_transformation_parameter',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='controlitem',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Control Element'), (1, 'Display Value')], default=0),
        ),
    ]
