# Generated by Django 2.2.8 on 2020-09-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hmi", "0027_auto_20200915_1407"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controlitem",
            name="display_value_transformation_parameter",
            field=models.CharField(blank=True, default="", max_length=400, null=True),
        ),
    ]
