# Generated by Django 2.2.8 on 2020-09-18 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hmi", "0030_auto_20200918_0842"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processflowdiagramitem",
            name="label",
        ),
        migrations.RemoveField(
            model_name="processflowdiagramitem",
            name="type",
        ),
        migrations.RemoveField(
            model_name="processflowdiagramitem",
            name="variable",
        ),
        migrations.AddField(
            model_name="processflowdiagramitem",
            name="control_item",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hmi.ControlItem",
            ),
        ),
        migrations.AlterField(
            model_name="displayvalueoption",
            name="color_1",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="color_1",
                to="pyscada.Color",
            ),
        ),
    ]
