# Generated by Django 2.2.8 on 2020-10-02 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hmi", "0038_auto_20200929_1410"),
    ]

    operations = [
        migrations.RenameField(
            model_name="displayvalueoption",
            old_name="display_value_color_type",
            new_name="color_type",
        ),
        migrations.RenameField(
            model_name="displayvalueoption",
            old_name="display_value_mode",
            new_name="mode",
        ),
        migrations.RenameField(
            model_name="dropdown",
            old_name="title",
            new_name="label",
        ),
        migrations.RemoveField(
            model_name="displayvalueoption",
            name="display_value_transformation",
        ),
        migrations.RemoveField(
            model_name="displayvalueoption",
            name="display_value_transformation_parameter",
        ),
        migrations.AddField(
            model_name="displayvalueoption",
            name="timestamp_conversion",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "Timestamp to local date"),
                    (2, "Timestamp to local time"),
                    (3, "Timestamp to local date and time"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="displayvalueoption",
            name="color_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="color_1",
                to="pyscada.Color",
            ),
        ),
        migrations.AlterField(
            model_name="dropdown",
            name="variable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pyscada.Variable",
            ),
        ),
        migrations.AlterField(
            model_name="dropdown",
            name="variable_property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pyscada.VariableProperty",
            ),
        ),
        migrations.DeleteModel(
            name="DropDownItem",
        ),
    ]
