# Generated by Django 2.2.17 on 2020-12-01 21:00

from django.db import migrations, models

from pyscada.hmi.models import Chart, ChartAxis
from pyscada.models import Variable

from time import time
import logging

logger = logging.getLogger(__name__)

def move_chart_axis(apps, schema_editor):
    chart_set = Chart.objects.all()
    count = 0
    timeout = time() + 60 * 5
    for item in chart_set:
        axis = ChartAxis(label=item.y_axis_label,
                         min=item.y_axis_min,
                         max=item.y_axis_max,
                         show_plot_points=item.show_plot_points,
                         show_plot_lines=item.show_plot_lines,
                         stack=False,
                         chart=item,
                         )
        axis.save()
        for v in item.variables.all():
            axis.variables.add(Variable.objects.get(id=v.id))
        axis.save()

        if time() > timeout:
            break

        count += 1

    logger.info('wrote %d lines in total\n' % count)


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0045_auto_20201201_2100'),
    ]

    operations = [
        migrations.RunPython(move_chart_axis),
        migrations.RemoveField(
            model_name='chart',
            name='show_plot_lines',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='show_plot_points',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='variables',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='y_axis_label',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='y_axis_max',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='y_axis_min',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='y_axis_uniquescale',
        ),
    ]
