# Generated by Django 2.2.8 on 2021-12-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hmi", "0056_auto_20211210_1608"),
    ]

    operations = [
        migrations.AddField(
            model_name="processflowdiagram",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "HTML"), (1, "SVG")],
                default=0,
                help_text="HTML is not responsive and can display control element<br>SVG is responsive and cannot display control element",
            ),
        ),
        migrations.AddField(
            model_name="processflowdiagramitem",
            name="font_size",
            field=models.PositiveSmallIntegerField(default=14),
        ),
    ]
