# Generated by Django 3.2 on 2022-05-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hmi", "0059_alter_view_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartaxis",
            name="show_bars",
            field=models.BooleanField(default=False, help_text="Show bars"),
        ),
    ]
