# Generated by Django 3.2 on 2023-01-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0066_auto_20221205_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cssclass',
            options={'verbose_name_plural': 'Css Classes'},
        ),
    ]
