# Generated by Django 4.2.1 on 2023-06-05 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hmi", "0072_alter_groupdisplaypermission_hmi_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processflowdiagramitem",
            name="control_item",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hmi.controlitem",
            ),
        ),
    ]
