# Generated by Django 4.2.1 on 2023-06-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hmi", "0073_alter_processflowdiagramitem_control_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cssclass",
            name="css_class",
            field=models.CharField(default="", max_length=250),
        ),
    ]
