# Generated by Django 4.2.1 on 2023-06-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hmi", "0074_alter_cssclass_css_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processflowdiagram",
            name="url_height",
            field=models.PositiveIntegerField(default="100", editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="processflowdiagram",
            name="url_width",
            field=models.PositiveIntegerField(default="100", editable=False, null=True),
        ),
    ]
