# Generated by Django 4.2.5 on 2023-11-22 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hmi", "0076_displayvalueoptiontemplate_transformdata_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransformDataCountValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                (
                    "display_value_option",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hmi.displayvalueoption",
                    ),
                ),
            ],
        ),
    ]
