# Generated by Django 4.2.5 on 2024-02-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hmi", "0077_transformdatacountvalue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="base_filename",
            field=models.CharField(
                default="base",
                help_text="Enter the filename without '.html'",
                max_length=400,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="view_filename",
            field=models.CharField(
                default="view",
                help_text="Enter the filename without '.html'",
                max_length=400,
            ),
        ),
    ]
