# Generated by Django 5.0.3 on 2024-07-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hmi", "0078_alter_theme_base_filename_alter_theme_view_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="displayvalueoption",
            name="from_timestamp_offset",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=None,
                help_text="Manage the value to be displayed if there is no data within the specified time interval.<br>If the field is empty, the last known data before the specified time interval will be displayed.<br>Set a value to add an offset in milliseconds before the start of the specified time interval.",
                null=True,
            ),
        ),
    ]
