# Generated by Django 5.2.9 on 2026-01-13 08:55

from django.db import migrations, models
import django.db.models.deletion
from django.db.models.fields.related import OneToOneRel

import logging

logger = logging.getLogger(__name__)


def create_unauthenticated_users_group_display_permission(apps, schema_editor):
    gdp = apps.get_model("hmi", "GroupDisplayPermission")

    g = gdp.objects.get_or_create(hmi_group=None, unauthenticated_users=True)

    if g[1]:
        logger.info("Unauthenticated users GroupDisplayPermission Created\n")


def delete_unauthenticated_users_group_display_permission(apps, schema_editor):
    gdp = apps.get_model("hmi", "GroupDisplayPermission")

    g = gdp.objects.filter(hmi_group=None, unauthenticated_users=True).delete()

    if g[1]:
        logger.info("Unauthenticated users GroupDisplayPermission Deleted\n")

class Migration(migrations.Migration):

    dependencies = [
        ("hmi", "0080_view_default_time_delta"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupdisplaypermission",
            name="unauthenticated_users",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            create_unauthenticated_users_group_display_permission, delete_unauthenticated_users_group_display_permission
        ),
    ]
