# Generated by Django 5.2.10 on 2026-02-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0081_groupdisplaypermission_unauthenticated_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=400)),
                ('description', models.TextField(default='', null=True, verbose_name='Description')),
                ('url', models.URLField()),
                ('logo', models.ImageField(blank=True, upload_to='img/', verbose_name='Overview Picture')),
                ('visible', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
