# Generated by Django 5.2.10 on 2026-02-04 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0082_externalview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalViewGroupDisplayPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'allow'), (1, 'exclude')], default=0, help_text='If allow: only selected items can be seen by the group.<br>If exclude: allows all items except the selected ones.')),
                ('external_view', models.ManyToManyField(blank=True, related_name='groupdisplaypermission', to='hmi.externalview')),
                ('group_display_permission', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hmi.groupdisplaypermission')),
            ],
        ),
    ]
