# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phantdevice',
            name='public_key',
            field=models.SlugField(default='....................', max_length=20, unique=True),
        ),
    ]
