# Generated by Django 5.2.10 on 2026-02-02 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pyscada', '0115_remove_recordeddata_variable_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='DjangoDatabase',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('data_model_app_name', models.CharField(max_length=50)),
                        ('data_model_name', models.CharField(max_length=50)),
                        ('datasource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyscada.datasource')),
                    ],
                    options={
                        'db_table': 'pyscada_djangodatabase',
                    },
                ),
                migrations.CreateModel(
                    name='RecordedData',
                    fields=[
                        ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                        ('date_saved', models.DateTimeField(blank=True, db_index=True, null=True)),
                        ('value_boolean', models.BooleanField(blank=True, default=False)),
                        ('value_int16', models.SmallIntegerField(blank=True, null=True)),
                        ('value_int32', models.IntegerField(blank=True, null=True)),
                        ('value_int64', models.BigIntegerField(blank=True, null=True)),
                        ('value_float64', models.FloatField(blank=True, null=True)),
                        ('variable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyscada.variable')),
                    ],
                    options={
                        'db_table': 'pyscada_recordeddata',
                    },
                ),
                migrations.CreateModel(
                    name='RecordedDataOld',
                    fields=[
                        ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                        ('value_boolean', models.BooleanField(blank=True, default=False)),
                        ('value_int16', models.SmallIntegerField(blank=True, null=True)),
                        ('value_int32', models.IntegerField(blank=True, null=True)),
                        ('value_int64', models.BigIntegerField(blank=True, null=True)),
                        ('value_float64', models.FloatField(blank=True, null=True)),
                        ('variable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyscada.variable')),
                    ],
                    options={
                        'db_table': 'pyscada_recordeddataold',
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
